<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSp3zx85\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSp3zx85/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSp3zx85.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSp3zx85\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSp3zx85\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sp3zx85',
    'container.build_id' => '0b7157ee',
    'container.build_time' => 1728915930,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSp3zx85');
