<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF9S44kN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF9S44kN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF9S44kN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF9S44kN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF9S44kN\App_KernelDevDebugContainer([
    'container.build_hash' => 'F9S44kN',
    'container.build_id' => '5ef3cd67',
    'container.build_time' => 1726480915,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF9S44kN');
